/* Auto-generated by CMake — do not edit */
#ifdef __cplusplus
extern "C" {
#endif
struct decoder *mp3_plugin_init(void);
struct decoder *mpg123_plugin_init(void);
struct decoder *aac_plugin_init(void);
struct decoder *vorbis_plugin_init(void);
struct decoder *opus_plugin_init(void);
struct decoder *flac_plugin_init(void);
struct decoder *musepack_plugin_init(void);
struct decoder *wavpack_plugin_init(void);
struct decoder *sndfile_plugin_init(void);
struct decoder *modplug_plugin_init(void);
struct decoder *speex_plugin_init(void);
struct decoder *sidplayfp_plugin_init(void);
struct decoder *ffmpeg_plugin_init(void);

#ifdef __cplusplus
}
#endif
