// src/audio/decoder.cpp
// SPDX-License-Identifier: GPL-3.0-or-later
//
// mocf - Music on Console Framebuffer
// Copyright (C) 2004 Damian Pietras <daper@daper.net>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <cassert>
#include <cctype>
#include <cerrno>
#include <cstdarg>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <string>

#include "core/common.h"
#include "audio/decoder.h"
#include "library/files.h"
#include "core/log.h"
#include "io/io.h"
#include "core/options.h"
#include "decoders/decoder_protos.h"

/* Static table of all decoders compiled into the binary.  Entries are
 * generated by CMake into decoder_list.h based on the WITH_* options. */
static const struct
{
  const char *name;
  AudioPlugin *(*init)(void);
} decoder_table[] = {
#include "decoders/decoder_list.h"
};

#define PLUGINS_NUM (ARRAY_SIZE(decoder_table))

static struct plugin
{
  const char *name;
  AudioPlugin *decoder;
} plugins[PLUGINS_NUM > 0 ? PLUGINS_NUM : 1];

static int plugins_num = 0;

static bool have_tremor = false;

/* This structure holds the user's decoder preferences for audio formats. */
struct decoder_s_preference
{
  struct decoder_s_preference *next; /* chain pointer */
#ifdef DEBUG
  const char *source; /* entry in PreferredDecoders */
#endif
  int decoders;                  /* number of decoders */
  int decoder_list[PLUGINS_NUM]; /* decoder indices */
  char *subtype;                 /* MIME subtype or NULL */
  char type[];                   /* MIME type or filename extn */
};
typedef struct decoder_s_preference decoder_t_preference;
static decoder_t_preference *preferences = NULL;
static int default_decoder_list[PLUGINS_NUM];

static char *clean_mime_subtype(char *subtype)
{
  char *ptr;

  assert(subtype && subtype[0]);

  if (!strncasecmp(subtype, "x-", 2))
  {
    subtype += 2;
  }

  ptr = strchr(subtype, ';');
  if (ptr)
  {
    *ptr = 0x00;
  }

  return subtype;
}

/* Find a preference entry matching the given filename extension and/or
 * MIME media type, or NULL. */
static decoder_t_preference *lookup_preference(const char *extn,
                                               const char *file, char **mime)
{
  char *type, *subtype;
  decoder_t_preference *result;

  assert((extn && extn[0]) || (file && file[0]) || (mime && *mime && *mime[0]));

  type = NULL;
  subtype = NULL;
  for (result = preferences; result; result = result->next)
  {
    if (!result->subtype)
    {
      if (extn && !strcasecmp(result->type, extn))
      {
        break;
      }
    }
    else
    {
      if (!type)
      {
        if (mime && *mime == NULL && file && file[0])
        {
          if (options_get_bool("UseMimeMagic"))
          {
            *mime = file_mime_type(file);
          }
        }
        if (mime && *mime && strchr(*mime, '/'))
        {
          type = xstrdup(*mime);
        }
        if (type)
        {
          subtype = strchr(type, '/');
          *subtype++ = 0x00;
          subtype = clean_mime_subtype(subtype);
        }
      }

      if (type)
      {
        if (!strcasecmp(result->type, type) &&
            !strcasecmp(result->subtype, subtype))
        {
          break;
        }
      }
    }
  }

  free(type);
  return result;
}

/* Return the index of the first decoder able to handle files with the
 * given filename extension, or -1 if none can. */
static int find_extn_decoder(int *decoder_list, int count, const char *extn)
{
  int ix;

  assert(decoder_list);
  assert(RANGE(0, count, plugins_num));
  assert(extn && extn[0]);

  for (ix = 0; ix < count; ix += 1)
  {
    if (plugins[decoder_list[ix]].decoder->our_format_ext(extn))
    {
      return decoder_list[ix];
    }
  }

  return -1;
}

/* Return the index of the first decoder able to handle audio with the
 * given MIME media type, or -1 if none can. */
static int find_mime_decoder(int *decoder_list, int count, const char *mime)
{
  int ix;

  assert(decoder_list);
  assert(RANGE(0, count, plugins_num));
  assert(mime && mime[0]);

  for (ix = 0; ix < count; ix += 1)
  {
    if (plugins[decoder_list[ix]].decoder->our_format_mime(mime))
    {
      return decoder_list[ix];
    }
  }

  return -1;
}

/* Return the index of the first decoder able to handle audio with the
 * given filename extension and/or MIME media type, or -1 if none can. */
static int find_decoder(const char *extn, const char *file, char **mime)
{
  int result;
  decoder_t_preference *pref;

  assert((extn && extn[0]) || (file && file[0]) || (mime && *mime));

  pref = lookup_preference(extn, file, mime);
  if (pref)
  {
    if (pref->subtype)
    {
      return find_mime_decoder(pref->decoder_list, pref->decoders, *mime);
    }
    else
    {
      return find_extn_decoder(pref->decoder_list, pref->decoders, extn);
    }
  }

  result = -1;
  if (mime && *mime)
  {
    result = find_mime_decoder(default_decoder_list, plugins_num, *mime);
  }
  if (result == -1 && extn && *extn)
  {
    result = find_extn_decoder(default_decoder_list, plugins_num, extn);
  }

  return result;
}

/* Find the index in plugins table for the given file.
 * Return -1 if not found. */
static int find_type(const char *file)
{
  int result = -1;
  char *extn, *mime;

  extn = ext_pos(file);
  mime = NULL;

  result = find_decoder(extn, file, &mime);

  free(mime);
  return result;
}

int is_sound_file(const char *name) { return find_type(name) != -1 ? 1 : 0; }

/* Return short type name for the given file or NULL if not found.
 * Not thread safe! */
char *file_type_name(const char *file)
{
  int i;
  static char buf[4];

  i = find_type(file);
  if (i == -1)
  {
    return NULL;
  }

  memset(buf, 0, sizeof(buf));
  plugins[i].decoder->get_name(file, buf);

  /* Attempt a default name if we have nothing else. */
  if (!buf[0])
  {
    char *ext;

    ext = ext_pos(file);
    if (ext)
    {
      size_t len;

      len = strlen(ext);
      for (size_t ix = 0; ix < len; ix += 1)
      {
        if (ix > 1)
        {
          buf[2] = toupper(ext[len - 1]);
          break;
        }
        buf[ix] = toupper(ext[ix]);
      }
    }
  }

  if (!buf[0])
  {
    return NULL;
  }

  return buf;
}

AudioPlugin *get_decoder(const char *file)
{
  int i;

  i = find_type(file);
  if (i != -1)
  {
    return plugins[i].decoder;
  }

  return NULL;
}

/* Given a decoder pointer, return its name. */
const char *get_decoder_name(const AudioPlugin *decoder)
{
  int ix;
  const char *result = NULL;

  assert(decoder);

  for (ix = 0; ix < plugins_num; ix += 1)
  {
    if (plugins[ix].decoder == decoder)
    {
      result = plugins[ix].name;
      break;
    }
  }

  assert(result);

  return result;
}

/* Return the index for a decoder of the given name, or plugins_num if
 * not found. */
static int lookup_decoder_by_name(const char *name)
{
  int result;

  assert(name && name[0]);

  result = 0;
  while (result < plugins_num)
  {
    if (!strcasecmp(plugins[result].name, name))
    {
      break;
    }
    result += 1;
  }

  return result;
}

/* Return a string of concatenated driver names. */
static char *list_decoder_names(int *decoder_list, int count)
{
  int ix;
  std::string result;
  lists_t_strs *names;

  if (count == 0)
  {
    return xstrdup("");
  }

  names = lists_strs_new(count);
  for (ix = 0; ix < count; ix += 1)
  {
    lists_strs_append(names, plugins[decoder_list[ix]].name);
  }

  if (have_tremor)
  {
    ix = lists_strs_find(names, "vorbis");
    if (ix < lists_strs_size(names))
    {
      lists_strs_replace(names, ix, "vorbis(tremor)");
    }
  }

  ix = lists_strs_find(names, "ffmpeg");
  if (ix < lists_strs_size(names))
  {
#if defined(HAVE_FFMPEG)
    lists_strs_replace(names, ix, "ffmpeg");
#elif defined(HAVE_LIBAV)
    lists_strs_replace(names, ix, "ffmpeg(libav)");
#else
    lists_strs_replace(names, ix, "ffmpeg/libav");
#endif
  }

  result = lists_strs_fmt(names, " %s");
  lists_strs_free(names);

  return xstrdup(result.c_str());
}


/* Create a new preferences entry and initialise it. */
static decoder_t_preference *make_preference(const char *prefix)
{
  decoder_t_preference *result;

  assert(prefix && prefix[0]);

  result = (decoder_t_preference *)xmalloc(
      offsetof(decoder_t_preference, type) + strlen(prefix) + 1);
  result->next = NULL;
  result->decoders = 0;
  strcpy(result->type, prefix);
  result->subtype = strchr(result->type, '/');
  if (result->subtype)
  {
    *result->subtype++ = 0x00;
    result->subtype = clean_mime_subtype(result->subtype);
  }

  return result;
}

/* Is the given decoder (by index) already in the decoder list for 'pref'? */
static bool is_listed_decoder(decoder_t_preference *pref, int d)
{
  int ix;
  bool result;

  assert(pref);
  assert(d >= 0);

  result = false;
  for (ix = 0; ix < pref->decoders; ix += 1)
  {
    if (d == pref->decoder_list[ix])
    {
      result = true;
      break;
    }
  }

  return result;
}

/* Add the named decoder (if valid) to a preferences decoder list. */
static void load_each_decoder(decoder_t_preference *pref, const char *name)
{
  int d;

  assert(pref);
  assert(name && name[0]);

  d = lookup_decoder_by_name(name);

  /* Drop unknown decoders. */
  if (d == plugins_num)
  {
    return;
  }

  /* Drop duplicate decoders. */
  if (is_listed_decoder(pref, d))
  {
    return;
  }

  pref->decoder_list[pref->decoders++] = d;

  return;
}

/* Build a preference's decoder list. */
static void load_decoders(decoder_t_preference *pref, lists_t_strs *tokens)
{
  int ix, dx, asterisk_at;
  int decoder[PLUGINS_NUM];
  const char *name;

  assert(pref);
  assert(tokens);

  asterisk_at = -1;

  /* Add the index of each known decoder to the decoders list.
   * Note the position following the first asterisk. */
  for (ix = 1; ix < lists_strs_size(tokens); ix += 1)
  {
    name = lists_strs_at(tokens, ix).c_str();
    if (strcmp(name, "*"))
    {
      load_each_decoder(pref, name);
    }
    else if (asterisk_at == -1)
    {
      asterisk_at = pref->decoders;
    }
  }

  if (asterisk_at == -1)
  {
    return;
  }

  dx = 0;

  /* Find decoders not already listed. */
  for (ix = 0; ix < plugins_num; ix += 1)
  {
    if (!is_listed_decoder(pref, ix))
    {
      decoder[dx++] = ix;
    }
  }

  /* Splice asterisk decoders into the decoder list. */
  for (ix = 0; ix < dx; ix += 1)
  {
    pref->decoder_list[pref->decoders++] = pref->decoder_list[asterisk_at + ix];
    pref->decoder_list[asterisk_at + ix] = decoder[ix];
  }

  assert(RANGE(0, pref->decoders, plugins_num));
}

/* Add a new preference for an audio format. */
static void load_each_preference(const char *preference)
{
  const char *prefix;
  lists_t_strs *tokens;
  decoder_t_preference *pref;

  assert(preference && preference[0]);

  tokens = lists_strs_new(4);
  lists_strs_split(tokens, preference, "(,)");
  prefix = lists_strs_at(tokens, 0).c_str();
  pref = make_preference(prefix);
#ifdef DEBUG
  pref->source = preference;
#endif
  load_decoders(pref, tokens);
  pref->next = preferences;
  preferences = pref;
  lists_strs_free(tokens);
}

/* Load all preferences given by the user in PreferredDecoders. */
static void load_preferences()
{
  int ix;
  const char *preference;
  lists_t_strs *list;

  list = options_get_list("PreferredDecoders");

  for (ix = 0; ix < lists_strs_size(list); ix += 1)
  {
    preference = lists_strs_at(list, ix).c_str();
    load_each_preference(preference);
  }

#ifdef DEBUG
  {
    char *names;
    decoder_t_preference *pref;

    for (pref = preferences; pref; pref = pref->next)
    {
      names = list_decoder_names(pref->decoder_list, pref->decoders);
      debug("%s:%s", pref->source, names);
      free(names);
    }
  }
#endif
}

static void load_plugins(int debug_info)
{
  size_t ix;
  char *names;

  (void)debug_info;

  for (ix = 0; ix < PLUGINS_NUM; ix += 1)
  {
    plugins[ix].decoder = decoder_table[ix].init();
    if (!plugins[ix].decoder)
    {
      fatal("Decoder \"%s\" returned NULL from init", decoder_table[ix].name);
    }
    if (plugins[ix].decoder->api_version != DECODER_API_VERSION)
    {
      fatal("Decoder \"%s\" uses a different API version", decoder_table[ix].name);
    }
    plugins[ix].name = decoder_table[ix].name;
    debug("Registered %s decoder", plugins[ix].name);
    plugins[ix].decoder->init();
    plugins_num += 1;
  }

  if (plugins_num == 0)
  {
    fatal("No decoder plugins have been loaded!");
  }

#ifdef HAVE_TREMOR
  have_tremor = true;
#endif

  for (ix = 0; ix < (size_t)plugins_num; ix += 1)
  {
    default_decoder_list[ix] = (int)ix;
  }

  names = list_decoder_names(default_decoder_list, plugins_num);
  logit("Loaded %d decoders:%s", plugins_num, names);
  free(names);
}

void decoder_init(int debug_info)
{
  load_plugins(debug_info);
  load_preferences();
}

static void cleanup_decoders()
{
  int ix;

  for (ix = 0; ix < plugins_num; ix++)
  {
    plugins[ix].decoder->destroy();
    /* plugins[ix].name points into decoder_table — not malloc'd. */
  }
}

static void cleanup_preferences()
{
  decoder_t_preference *pref, *next;

  for (pref = preferences; pref; pref = next)
  {
    next = pref->next;
    free(pref);
  }

  preferences = NULL;
}

void decoder_cleanup()
{
  cleanup_decoders();
  cleanup_preferences();
}

/* Fill the error structure with an error of a given type and message.
 * strerror(add_errno) is appended at the end of the message if add_errno != 0.
 * This is thread safe; use this instead of constructs using strerror(). */
void decoder_error(struct decoder_error *error,
                   const enum decoder_error_type type, const int add_errno,
                   const char *format, ...)
{
  va_list va;

  error->type = type;

  va_start(va, format);
  error->err = format_msg_va(format, va);
  va_end(va);

  if (add_errno)
  {
    error->err += xstrerror(add_errno);
  }
}

/* Initialize the decoder_error structure. */
void decoder_error_init(struct decoder_error *error)
{
  error->type = ERROR_OK;
  error->err.clear();
}

/* Set the decoder_error structure to contain "success" information. */
void decoder_error_clear(struct decoder_error *error)
{
  error->type = ERROR_OK;
  error->err.clear();
}

void decoder_error_copy(struct decoder_error *dst,
                        const struct decoder_error *src)
{
  dst->type = src->type;
  dst->err = src->err;
}

/* Return the error text from the decoder_error variable. */
const char *decoder_error_text(const struct decoder_error *error)
{
  return error->err.c_str();
}

// EOF
