// src/audio/decoder.cpp
// SPDX-License-Identifier: GPL-3.0-or-later
//
// mocf - Music on Console Framebuffer
// Copyright (C) 2004 Damian Pietras <daper@daper.net>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <cassert>
#include <cctype>
#include <cerrno>
#include <cstdarg>
#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
#include <memory>

#include "core/common.h"
#include "audio/decoder.h"
#include "library/files.h"
#include "core/log.h"
#include "io/io.h"
#include "core/options.h"
#include "decoders/decoder_protos.h"

/* Static table of all decoders compiled into the binary.  Entries are
 * generated by CMake into decoder_list.h based on the WITH_* options. */
static const struct
{
  const char *name;
  AudioPlugin *(*init)();
} decoder_table[] = {
#include "decoders/decoder_list.h"
};

#define PLUGINS_NUM (std::size(decoder_table))

static struct plugin
{
  const char *name;
  AudioPlugin *decoder;
} plugins[PLUGINS_NUM > 0 ? PLUGINS_NUM : 1];

static int plugins_num = 0;

static bool have_tremor = false;

/* This structure holds the user's decoder preferences for audio formats. */
struct decoder_s_preference
{
#ifdef DEBUG
  std::string source; /* entry in PreferredDecoders */
#endif
  int decoders;                  /* number of decoders */
  int decoder_list[PLUGINS_NUM]; /* decoder indices */
  std::string subtype;           /* MIME subtype or empty */
  std::string type;              /* MIME type or filename extn */
};
typedef struct decoder_s_preference decoder_t_preference;
static std::vector<std::unique_ptr<decoder_t_preference>> preferences;
static int default_decoder_list[PLUGINS_NUM];

static std::string clean_mime_subtype(std::string subtype)
{
  if (subtype.length() >= 2 && !strncasecmp(subtype.c_str(), "x-", 2))
  {
    subtype = subtype.substr(2);
  }

  size_t ptr = subtype.find(';');
  if (ptr != std::string::npos)
  {
    subtype.resize(ptr);
  }

  return subtype;
}

/* Split a string on any character in delims, mirroring the old
 * lists_strs_split(): consecutive and leading/trailing delimiters do
 * not produce empty entries. */
static std::vector<std::string> split_on_chars(const char *s, const char *delims)
{
  std::vector<std::string> result;
  std::string buf(s);
  size_t start = 0;

  while (start < buf.size())
  {
    size_t end = buf.find_first_of(delims, start);
    if (end == std::string::npos)
    {
      result.push_back(buf.substr(start));
      break;
    }
    if (end > start)
    {
      result.push_back(buf.substr(start, end - start));
    }
    start = end + 1;
  }

  return result;
}

/* Find a preference entry matching the given filename extension and/or
 * MIME media type, or nullptr. */
static decoder_t_preference *lookup_preference(const char *extn,
                                               const char *file, std::string &mime)
{
  std::string type, subtype;

  assert((extn && extn[0]) || (file && file[0]) || !mime.empty());

  for (auto &up : preferences)
  {
    decoder_t_preference *result = up.get();

    if (result->subtype.empty())
    {
      if (extn && !strcasecmp(result->type.c_str(), extn))
      {
        return result;
      }
    }
    else
    {
      if (type.empty())
      {
        if (mime.empty() && file && file[0])
        {
          if (options_get_bool("UseMimeMagic"))
          {
            mime = file_mime_type(file);
          }
        }
        if (!mime.empty())
        {
          size_t slash = mime.find('/');
          if (slash != std::string::npos)
          {
            type = mime.substr(0, slash);
            subtype = clean_mime_subtype(mime.substr(slash + 1));
          }
        }
      }

      if (!type.empty())
      {
        if (!strcasecmp(result->type.c_str(), type.c_str()) &&
            !strcasecmp(result->subtype.c_str(), subtype.c_str()))
        {
          return result;
        }
      }
    }
  }

  return nullptr;
}

/* Return the index of the first decoder able to handle files with the
 * given filename extension, or -1 if none can. */
static int find_extn_decoder(int *decoder_list, int count, const char *extn)
{
  int ix;

  assert(decoder_list);
  assert(in_closed_range(0, count, plugins_num));
  assert(extn && extn[0]);

  for (ix = 0; ix < count; ix += 1)
  {
    if (plugins[decoder_list[ix]].decoder->our_format_ext(extn))
    {
      return decoder_list[ix];
    }
  }

  return -1;
}

/* Return the index of the first decoder able to handle audio with the
 * given MIME media type, or -1 if none can. */
static int find_mime_decoder(int *decoder_list, int count, const char *mime)
{
  int ix;

  assert(decoder_list);
  assert(in_closed_range(0, count, plugins_num));
  assert(mime && mime[0]);

  for (ix = 0; ix < count; ix += 1)
  {
    if (plugins[decoder_list[ix]].decoder->our_format_mime(mime))
    {
      return decoder_list[ix];
    }
  }

  return -1;
}

/* Return the index of the first decoder able to handle audio with the
 * given filename extension and/or MIME media type, or -1 if none can. */
static int find_decoder(const char *extn, const char *file, std::string &mime)
{
  int result;
  decoder_t_preference *pref;

  assert((extn && extn[0]) || (file && file[0]) || !mime.empty());

  pref = lookup_preference(extn, file, mime);
  if (pref)
  {
    if (!pref->subtype.empty())
    {
      return find_mime_decoder(pref->decoder_list, pref->decoders, mime.c_str());
    }
    else
    {
      return find_extn_decoder(pref->decoder_list, pref->decoders, extn);
    }
  }

  result = -1;
  if (!mime.empty())
  {
    result = find_mime_decoder(default_decoder_list, plugins_num, mime.c_str());
  }
  if (result == -1 && extn && *extn)
  {
    result = find_extn_decoder(default_decoder_list, plugins_num, extn);
  }

  return result;
}

/* Find the index in plugins table for the given file.
 * Return -1 if not found. */
static int find_type(const char *file)
{
  int result = -1;
  char *extn;
  std::string mime;

  extn = ext_pos(file);

  result = find_decoder(extn, file, mime);

  return result;
}

int is_sound_file(const char *name) { return find_type(name) != -1 ? 1 : 0; }

/* Return short type name for the given file, or an empty string if the
 * type could not be determined. */
std::string file_type_name(const char *file)
{
  int i;
  std::string name;

  i = find_type(file);
  if (i == -1)
  {
    return "";
  }

  name = plugins[i].decoder->get_name(file);

  /* Attempt a default name if we have nothing else. */
  if (name.empty())
  {
    char *ext;

    ext = ext_pos(file);
    if (ext)
    {
      size_t len;

      len = strlen(ext);
      for (size_t ix = 0; ix < len; ix += 1)
      {
        if (ix > 1)
        {
          name += static_cast<char>(toupper(ext[len - 1]));
          break;
        }
        name += static_cast<char>(toupper(ext[ix]));
      }
    }
  }

  return name;
}

AudioPlugin *get_decoder(const char *file)
{
  int i;

  i = find_type(file);
  if (i != -1)
  {
    return plugins[i].decoder;
  }

  return nullptr;
}

/* Given a decoder pointer, return its name. */
const char *get_decoder_name(const AudioPlugin *decoder)
{
  int ix;
  const char *result = nullptr;

  assert(decoder);

  for (ix = 0; ix < plugins_num; ix += 1)
  {
    if (plugins[ix].decoder == decoder)
    {
      result = plugins[ix].name;
      break;
    }
  }

  assert(result);

  return result;
}

/* Return the index for a decoder of the given name, or plugins_num if
 * not found. */
static int lookup_decoder_by_name(const char *name)
{
  int result;

  assert(name && name[0]);

  result = 0;
  while (result < plugins_num)
  {
    if (!strcasecmp(plugins[result].name, name))
    {
      break;
    }
    result += 1;
  }

  return result;
}

/* Return a string of concatenated driver names. */
static std::string list_decoder_names(int *decoder_list, int count)
{
  int ix;
  std::string result;
  std::vector<std::string> names;

  if (count == 0)
  {
    return "";
  }

  names.reserve(count);
  for (ix = 0; ix < count; ix += 1)
  {
    names.push_back(plugins[decoder_list[ix]].name);
  }

  if (have_tremor)
  {
    auto it = std::find(names.begin(), names.end(), "vorbis");
    if (it != names.end())
    {
      *it = "vorbis(tremor)";
    }
  }

  auto it = std::find(names.begin(), names.end(), "ffmpeg");
  if (it != names.end())
  {
#if defined(HAVE_FFMPEG)
    *it = "ffmpeg";
#elif defined(HAVE_LIBAV)
    *it = "ffmpeg(libav)";
#else
    *it = "ffmpeg/libav";
#endif
  }

  for (const auto &name : names)
  {
    if (!result.empty()) result += " ";
    result += name;
  }

  return result;
}


/* Create a new preferences entry and initialise it. */
static std::unique_ptr<decoder_t_preference> make_preference(const char *prefix)
{
  auto result = std::make_unique<decoder_t_preference>();

  assert(prefix && prefix[0]);

  result->decoders = 0;
  result->subtype = "";

  std::string p(prefix);
  size_t slash = p.find('/');
  if (slash != std::string::npos)
  {
    result->type = p.substr(0, slash);
    result->subtype = clean_mime_subtype(p.substr(slash + 1));
  }
  else
  {
    result->type = p;
  }

  return result;
}

/* Is the given decoder (by index) already in the decoder list for 'pref'? */
static bool is_listed_decoder(decoder_t_preference *pref, int d)
{
  int ix;
  bool result;

  assert(pref);
  assert(d >= 0);

  result = false;
  for (ix = 0; ix < pref->decoders; ix += 1)
  {
    if (d == pref->decoder_list[ix])
    {
      result = true;
      break;
    }
  }

  return result;
}

/* Add the named decoder (if valid) to a preferences decoder list. */
static void load_each_decoder(decoder_t_preference *pref, const char *name)
{
  int d;

  assert(pref);
  assert(name && name[0]);

  d = lookup_decoder_by_name(name);

  /* Drop unknown decoders. */
  if (d == plugins_num)
  {
    return;
  }

  /* Drop duplicate decoders. */
  if (is_listed_decoder(pref, d))
  {
    return;
  }

  pref->decoder_list[pref->decoders++] = d;

  return;
}

/* Build a preference's decoder list. */
static void load_decoders(decoder_t_preference *pref, const std::vector<std::string> &tokens)
{
  int ix, dx, asterisk_at;
  int decoder[PLUGINS_NUM];
  const char *name;

  assert(pref);

  asterisk_at = -1;

  /* Add the index of each known decoder to the decoders list.
   * Note the position following the first asterisk. */
  for (ix = 1; ix < static_cast<int>(tokens.size()); ix += 1)
  {
    name = tokens[ix].c_str();
    if (strcmp(name, "*"))
    {
      load_each_decoder(pref, name);
    }
    else if (asterisk_at == -1)
    {
      asterisk_at = pref->decoders;
    }
  }

  if (asterisk_at == -1)
  {
    return;
  }

  dx = 0;

  /* Find decoders not already listed. */
  for (ix = 0; ix < plugins_num; ix += 1)
  {
    if (!is_listed_decoder(pref, ix))
    {
      decoder[dx++] = ix;
    }
  }

  /* Splice asterisk decoders into the decoder list. */
  for (ix = 0; ix < dx; ix += 1)
  {
    pref->decoder_list[pref->decoders++] = pref->decoder_list[asterisk_at + ix];
    pref->decoder_list[asterisk_at + ix] = decoder[ix];
  }

  assert(in_closed_range(0, pref->decoders, plugins_num));
}

/* Add a new preference for an audio format. */
static void load_each_preference(const char *preference)
{
  const char *prefix;
  std::vector<std::string> tokens;

  assert(preference && preference[0]);

  tokens = split_on_chars(preference, "(,)");
  prefix = tokens[0].c_str();
  auto pref = make_preference(prefix);
#ifdef DEBUG
  pref->source = preference;
#endif
  load_decoders(pref.get(), tokens);
  preferences.insert(preferences.begin(), std::move(pref));
}

/* Load all preferences given by the user in PreferredDecoders. */
static void load_preferences()
{
  for (const auto &preference : options_get_list("PreferredDecoders"))
  {
    load_each_preference(preference.c_str());
  }

#ifdef DEBUG
  for (const auto &pref : preferences)
  {
    std::string names = list_decoder_names(pref->decoder_list, pref->decoders);
    debug("%s:%s", pref->source.c_str(), names.c_str());
  }
#endif
}

static void load_plugins(int debug_info)
{
  size_t ix;

  (void)debug_info;

  for (ix = 0; ix < PLUGINS_NUM; ix += 1)
  {
    plugins[ix].decoder = decoder_table[ix].init();
    if (!plugins[ix].decoder)
    {
      fatal("Decoder \"%s\" returned nullptr from init", decoder_table[ix].name);
    }
    if (plugins[ix].decoder->api_version != DECODER_API_VERSION)
    {
      fatal("Decoder \"%s\" uses a different API version", decoder_table[ix].name);
    }
    plugins[ix].name = decoder_table[ix].name;
    debug("Registered %s decoder", plugins[ix].name);
    plugins[ix].decoder->init();
    plugins_num += 1;
  }

  if (plugins_num == 0)
  {
    fatal("No decoder plugins have been loaded!");
  }

#ifdef HAVE_TREMOR
  have_tremor = true;
#endif

  for (ix = 0; ix < static_cast<size_t>(plugins_num); ix += 1)
  {
    default_decoder_list[ix] = static_cast<int>(ix);
  }

  std::string names = list_decoder_names(default_decoder_list, plugins_num);
  logit("Loaded %d decoders: %s", plugins_num, names.c_str());
}

void decoder_init(int debug_info)
{
  load_plugins(debug_info);
  load_preferences();
}

static void cleanup_decoders()
{
  int ix;

  for (ix = 0; ix < plugins_num; ix++)
  {
    plugins[ix].decoder->destroy();
    /* plugins[ix].name points into decoder_table — not malloc'd. */
  }
}

static void cleanup_preferences()
{
  preferences.clear();
}

void decoder_cleanup()
{
  cleanup_decoders();
  cleanup_preferences();
}

/* Fill the error structure with an error of a given type and message.
 * strerror(add_errno) is appended at the end of the message if add_errno != 0.
 * This is thread safe; use this instead of constructs using strerror(). */
void decoder_error(struct decoder_error *error,
                   const enum decoder_error_type type, const int add_errno,
                   const char *format, ...)
{
  va_list va;

  error->type = type;

  va_start(va, format);
  error->err = format_msg_va(format, va);
  va_end(va);

  if (add_errno)
  {
    error->err += xstrerror(add_errno);
  }
}

/* Initialize the decoder_error structure. */
void decoder_error_init(struct decoder_error *error)
{
  error->type = ERROR_OK;
  error->err.clear();
}

/* Set the decoder_error structure to contain "success" information. */
void decoder_error_clear(struct decoder_error *error)
{
  error->type = ERROR_OK;
  error->err.clear();
}

void decoder_error_copy(struct decoder_error *dst,
                        const struct decoder_error *src)
{
  dst->type = src->type;
  dst->err = src->err;
}

/* Return the error text from the decoder_error variable. */
const char *decoder_error_text(const struct decoder_error *error)
{
  return error->err.c_str();
}

// EOF
